using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TrainDemoApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("using");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(" System;\n");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("using");
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write(" System.System.Collections.Generic;\n");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("using");
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write(" System.Linq;\n");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("using");
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write(" System.Text;\n");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("using");
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write(" System.Threading.Tasks;\n\n");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("namespace");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(" ConsoleApp1\n{\n");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("\tclass");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write(" Program");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("\n\t{\n");
            Console.ForegroundColor = ConsoleColor.DarkGreen; Console.Write("\t\t//單行註解\n");
            Console.ForegroundColor = ConsoleColor.DarkGreen; Console.Write("\t\t/*\n\t\t多行\n\t\t註解\n\t\t*/\n");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("\t\tstaice void ");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("Main");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("string");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("[");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("] ");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("args");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("\n\t\t{\n");
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write("\t\t\tSystem");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("Console");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"Hello World!!\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write("\t\t\tSystem");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("Console");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"HI,這是一個主控台程式。\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"C#語言示範\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"C#Demo\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".ForegroundColor = ");
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("ConsoleColor");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".Yellow;\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".BackgroundColor = ");
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("ConsoleColor");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".DarkGray;\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"1. 主控台應用程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"2. Window Form 應用程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"3. Web 應用程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("ResetColor");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"特殊的字元符號\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("\\\"");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("雙引號");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("\\\"");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("\\\\");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("反斜線");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("\\\\");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("\\\'");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("單引線");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("\\\'");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");            
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("\\");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("t");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("縮排");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");            
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("換行");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("\\");
            Console.ForegroundColor = ConsoleColor.DarkMagenta; Console.Write("n");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n\n");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("\t\t\tConsole");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"按Enter結束程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write("\t\t\tSystem");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("Console");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(".");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("ReadLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";\n");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("\t\t}\n");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("\t}\n");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("}\n");


            Console.ReadLine();
            
        }
    }
}
